/** Declaration file generated by dts-gen */

export = obj2gltf;

declare function obj2gltf(objPath: any, options: any): any;

declare namespace obj2gltf {
    const defaults: {
        binary: boolean;
        checkTransparency: boolean;
        inputUpAxis: string;
        metallicRoughness: boolean;
        outputUpAxis: string;
        packOcclusion: boolean;
        secure: boolean;
        separate: boolean;
        separateTextures: boolean;
        specularGlossiness: boolean;
        unlit: boolean;
        windingOrderSanitization: boolean;
    };

}

